name: MIG

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  HEADLESS_MODE: true


jobs:
  run-mig:
    runs-on: ubuntu-latest

    steps:
      - name: Clone MIG
        run: |
          git clone --recurse-submodules https://github.com/simone36050/mig.git
          cd mig
          git checkout headless2
          cd ..
        
      - name: Generate Tests
        run: |
          cd mig/testplans/spid-cie-oidc/implementations/spid-cie-oidc-django/
          bash generate_mr.sh --django

      - name: Build and run all components
        run: |
          cd mig/testplans/spid-cie-oidc/implementations/spid-cie-oidc-django/
          chmod +x build_and_run.sh
          ./build_and_run.sh

      - name: Wait for the server to start
        run: sleep 50

      - name: Run Tests
        run: |
          cd mig/testplans/spid-cie-oidc/implementations/spid-cie-oidc-django/
          python execute.py input/mig-t/tests/single/Passive.json input/mig-t/sessions --only-validate


